# -*- coding: utf-8 -*-
"""resize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UI4qtgi8EVmEFdBkoMKRJPOFO0urAl4W
"""

import os
import cv2
from google.colab.patches import cv2_imshow

images = os.listdir('/content/drive/My Drive/HW-1/images_256x256/')
images_out = '/content/drive/My Drive/HW-1/images_256x256/'


c = 1
for i in images:
    nm = '/content/drive/My Drive/HW-1/images/' + i
    image = cv2.imread(nm,1)
    
    image_resized = cv2.resize(image, (256, 256))
    
    nm = images_out+i[:i.find('.')]+'.jpg'

    cv2.imwrite(nm,image_resized)
    
    print(c)
    c += 1
